### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by txgo** [astoilkov/jsblocks-shopping-example#3]
```
/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:7188
              element.setAttribute(expression.attr, Expression.GetValue(contex
                      ^
TypeError: Cannot call method 'setAttribute' of undefined
    at updateExpression (/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:7188:23)
    at Function.blocks.eachRight (/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:182:9)
    at Function.blocks.extend.fn.base.update (/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:7168:18)
    at observable [as pages] (/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:7055:20)
    at eval (eval at executeCode (/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:11688:21), <anonymous>:14735:10)
    at /home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:10624:18
    at /home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:9577:11
    at ajax.success (/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:9673:13)
    at Object.Request.callSuccess (/home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:9307:9)
    at /home/xi/git/jsblocks-shopping-example/node_modules/blocks/node/blocks-node.js:12267:19

```

**Comment by astoilkov** [comment]
Hi,

Hmm. Yes I have an idea how to fix the error. What are the steps for reproducing the issue?

> Note that this is specific to the server-side rendering mechanism. If you run the application using `npm start` you will stop seeing the error. This could be helpful for now until the bug is fixed.

Thanks for your cooperation in advance.

**Comment by sethkrasnianski** [comment]
To reproduce this, visit /news or /news/:page and refresh once or twice.

**Comment by astoilkov** [comment]
Thanks a lot. I will fix this as soon as possible.

**Comment by astoilkov** [comment]
Sorry for taking this long but I have made couple of improvements to the server-side rendering. You could take a look at the commit [here](https://github.com/astoilkov/jsblocks/commit/cc46ce70635c396c554aadfea3e73892da6d13ea). Note that the changes will not be available through npm. After I test everything and make couple of more improvements I will make a release to make the changes available.

I am closing this issue.
