### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by pcdinh** [astoilkov/jsblocks-shopping-example#5]
Hi,

I am unable to launch the app. The following error has been logged

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'node' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prenode', 'node', 'postnode' ]
6 info prenode jsblocks-shopping-example@0.8.0
7 info node jsblocks-shopping-example@0.8.0
8 verbose unsafe-perm in lifecycle true
9 info jsblocks-shopping-example@0.8.0 Failed to exec node script
10 verbose stack Error: jsblocks-shopping-example@0.8.0 node: `opener http://localhost:8000 && node app.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid jsblocks-shopping-example@0.8.0
12 verbose cwd C:\Console2\m\jsblocks-shopping-example
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "node"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error jsblocks-shopping-example@0.8.0 node: `opener http://localhost:8000 && node app.js`
18 error Exit status 1
19 error Failed at the jsblocks-shopping-example@0.8.0 node script 'opener http://localhost:8000 && node app.js'.
19 error This is most likely a problem with the jsblocks-shopping-example package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     opener http://localhost:8000 && node app.js
19 error You can get their info via:
19 error     npm owner ls jsblocks-shopping-example
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by pcdinh** [comment]
It looks like that Windows permission caused that issue. I run it with `node app.js` and enabled node to access private network, it worked later on.

**Comment by astoilkov** [comment]
Happy to hear that. Closing this one.
